### PR TITLE
CONTRIB-6471 mod-questionnaire: fix rtl greaph report

### PR DESCRIPTION
**Pull request by AviMoto**
Fix rtl graph report

### CODE REVIEW

**Comment by nadavkav** [comment]
Hi @mchurchward, please see if you can review and integrate this. (as this can help us a lot)

**Comment by mchurchward** [comment]
Hi.
Can you rewrite the change using the Moodle "right_to_left" API function instead? While that checks the same language string, using the API function means that if Moodle changes the way to detect RTL languages in the future, this code won't break. You can see that function in lib/weblib.php.
Also, the change as provided violates some Moodle coding rules, in particular "if" statements need a space between the "if" and the opening parentheses. You can see that here - https://travis-ci.org/remotelearner/moodle-mod_questionnaire/jobs/147279908#L773

Once you made these changes, please submit the pull request again.

Thanks.

**Comment by mchurchward** [comment]
Hi. Are you able to do the requested changes to your pull request?

**Comment by AviMoto** [comment]
I update the code to use the right_to_left() function

**Pull request merged**
