### PR TITLE
Allow localized answer options to be displayed correctly in conditions.

### PR DESCRIPTION
**Pull request by lucaboesch**
This is also nice, I use it in our place since quite some times.
I've written a Behat test, too.
This becomes multilingual.
image
Best,
Luca

### CODE REVIEW

**Comment by mchurchward** [comment]
Hi Luca. You may want to grab the fixed GHA CI file from [this commit](https://github.com/PoetOS/moodle-mod_questionnaire/pull/460/commits/fc81ebdf15d387ed03c9852b6362d3402956763f) to fix your CI issues.

**Comment by lucaboesch** [comment]
Thanks, @mchurchward. That should be settled now.

**Comment by lucaboesch** [comment]
There's no conflict here any more, @mchurchward .

**Comment by lucaboesch** [comment]
I think this is still relevant, @mchurchward .

**Review by rezeau — APPROVED** [review]
Works as expected. Tested with the TinyMCE editor.

**Review by mchurchward — APPROVED** [review]

**Pull request merged**
