### PR TITLE
Fix for bug #50 file picker breaks

### PR DESCRIPTION
**Pull request by Syxton**

### CODE REVIEW

**Comment by Syxton** [comment]
The original commit was not tested thoroughly.  I hadn't fully figured out the Moodle file storage.  This should be good now.

**Comment by mchurchward** [comment]
Hi. Thanks for the merge. Could you file a bug in the Moodle tracker in the CONTRIB project with the "Module:Questionnaire" component? Describe what the bug was, how to test it and what the fix does?
Thanks.

**Comment by mchurchward** [comment]
I believe this is part of https://tracker.moodle.org/browse/CONTRIB-5940

**Comment by mchurchward** [comment]
Due to the code structure changing significantly, this request is no longer valid. If you wish to rework it to the new structure of 3.2 and higher, that would be great.

**Pull request closed without merging**
