### PR TITLE
CONTRIB-5909 Fix syntax to improve cross-db compatibility

### PR DESCRIPTION
**Pull request by danmarsden**
This hasn't been tested as well as I would like but has been deployed to a clients site. Would be good for someone to verify this before you merge it.

### CODE REVIEW

**Comment by timhunt** [comment]
That is a big step in the right direction, but since $resps is not used in the rest of the function, only $countresps, you should really use $DB->count_records for that.

**Comment by danmarsden** [comment]
good spotting Tim! - fixed and rebased.

I didn't look too closely at the rest of that file... the more I looked, the more I wanted to rewrite.. just never enough time.

**Comment by timhunt** [comment]
Thanks. I will leave it to Mike C to do a final review and merge.

**Comment by mchurchward** [comment]
Thanks guys. This looks fine - and necessary. Still not sure why the old code was giving an error though.

**Pull request merged**
