### PR TITLE
Fix XSS vulnerability

### PR DESCRIPTION
**Pull request by gthomas2**
I was able to create a question with javascript in it that alerted document.cookie - replacing 'noclean'=>true with 'noclean'=>false fixed that issue.

### CODE REVIEW

**Comment by timhunt** [comment]
Security in Moodle is tricky. We have different users with different levels of trust.

This is necessary because teachers may wish to embed usful educational things that require JavaScript.

So, the general rules is that teachers can do XSS but students can't. More accurately, certain capabilities have RISK_XSS included in the risk bitmask, and the default role definitions should only grant those capabilities to teachers and above.

So, this is not a bug, it is by design.

**Comment by timhunt** [comment]
Actually there is a bug, 'mod/questionnaire:editquestions' capability doesn not declare RISK_XSS. I guess all the capabilities should have their risks reviewed.

**Comment by gthomas2** [comment]
Thanks for clarifying this Tim

**Comment by mchurchward** [comment]
Handling in https://tracker.moodle.org/browse/CONTRIB-6919

**Pull request closed without merging**
