### PR TITLE
Adopt icon size to 24×24 with a smaller content as other icons.

### LINKED ISSUE #568: New monologo activity icon for Moodle 4.4
In Moodle 4.4, activity icons have been redesigned. They are still 24 x 24, but the content is smaller and doesn't fill the entire space. The icon for hotquestion should be modified accordingly, as in https://github.com/lucaboesch/moodle-mod_questionnaire/tree/iconsize.

image

### PR DESCRIPTION
**Pull request by lucaboesch**
This resolves #568

### CODE REVIEW

**Review by mchurchward — COMMENTED** [review]
Does this icon still look okay on earlier Moodle 4 versions?

**Comment by mchurchward** [comment]
Also, please rebase with the latest MOODLE_401_STABLE.

**Comment by lucaboesch** [comment]
Rebased and only one commit diff, @mchurchward !
It will look okay on elder versions.

**Review by mchurchward — APPROVED** [review]
Thanks.

**Pull request merged**
