### PR TITLE
Add 4.4 and main to matrix

### PR DESCRIPTION
**Pull request by aspark21**

### CODE REVIEW

**Comment by aspark21** [comment]
tests fail - https://github.com/aspark21/moodle-mod_questionnaire/actions/runs/10101874369

that's the point

**Review by mchurchward — CHANGES_REQUESTED** [review]
Thank you for this. Can you rebase with the latest MOODLE_401_STABLE to re-enable the CI tests?
I'm not sure we want 'main' yet.

**Comment by mchurchward** [comment]
I have [added 4.4 to the matrix](https://github.com/PoetOS/moodle-mod_questionnaire/commit/33096037711206df48e8ce86536414cca99f8453). I don't want "main" in there as it is not released yet.

**Comment by aspark21** [comment]
Yeah main will never be released but the point is that it gives you early visibility into things that need to change for the next version. If those tests fail you can always ignore them for a while.

At least we have found it useful with our own plugins

**Pull request closed without merging**
