### PR TITLE
Sectiontext qtype should not support feedback

### PR DESCRIPTION
**Pull request by rezeau**

### CODE REVIEW

**Comment by rezeau** [comment]
OOps! Just noticed that my PR contains changes in 2 files, which was not intended but does fix 2 issues:

1. In classes/question/sectiontext.php; sectiontext qtype (label) should not support feedback
2. in tests/behat/no_feedback_question_types.feature: current navigation to _Advanced settings_ and check that _I should not see "Feedback options"_ does not work as expected. This should be fixed by my PR.

**Review by mchurchward — CHANGES_REQUESTED** [review]
Looks good. Can you rebase/reapply against MOODLE_401_STABLE and resubmit?

**Review by mchurchward — APPROVED** [review]
All good

**Comment by mchurchward** [comment]
I rebased and created a [new pull request](https://github.com/PoetOS/moodle-mod_questionnaire/pull/547). Closing this one.

**Comment by mchurchward** [comment]
Aha. Just found #514

**Pull request closed without merging**
