### PR TITLE
Right align questions in RTL mode

### PR DESCRIPTION
**Pull request by nadavkav**

### CODE REVIEW

**Comment by nadavkav** [comment]
Any news about updating styles.css with above fixes?

**Comment by mchurchward** [comment]
Can you update it to a current branch? Also, can you describe the problem it addresses and how to verify that it solves that problem?
Thanks.

**Comment by nadavkav** [comment]
Ok. I will make PR for it also.

**Comment by nadavkav** [comment]
All elements marked in red needs to be right aligned (float) in RTL mode
In both "preview" and "edit" modes. Attaching screen captures if the issue:
image
And also:
image

**Comment by mchurchward** [comment]
Can you also post what it should look like after the fix?

**Comment by nadavkav** [comment]
Updated the patch. (as I found new minor fixes)

**Comment by nadavkav** [comment]
image

**Comment by nadavkav** [comment]
image

**Comment by nadavkav** [comment]
And just in case the double commit old patch is messed up, here are the final changes...
```
.dir-rtl#page-mod-questionnaire-questions .qcontainer .qnums,
.dir-rtl .qn-legend, 
.dir-rtl .qn-info { float: right; } 

.dir-rtl#page-mod-questionnaire-questions .qn-question { 
margin-right: 40px; margin-left:auto; 
}
.dir-rtl#page-mod-questionnaire-questions #region-main .mform .fitem .felement {margin:0;}
.dir-rtl.path-mod-questionnaire .floatprinticon {float: left;}
.dir-rtl.path-mod-questionnaire .raterow > td:first-child {
    text-align: right !important;
}
```

**Comment by nadavkav** [comment]
Checking...

**Comment by nadavkav** [comment]
Ok. some is fixed. (I am checking this in Boost, hope is that Ok with you)
1. Questionnaire Preview & "Answer the questions..." modes, text labels needs to be right aligned:
image
2. Redundant BS col-md-3 element in question edit page:
image

**Comment by mchurchward** [comment]
I'm not sure what needs to be done to correct that. I would have thought using renderers and templates would have resolved that. Maybe it still needs to be dealt with by CSS?

**Comment by nadavkav** [comment]
Should I propose a PR for this?

**Comment by nadavkav** [comment]
btw, the second issue is also relevant for the LTR version.
Did no one complained?

**Comment by nadavkav** [comment]
I can float the empty DIV to the left, and the DIV with the question to the right, in RTL mode.
considering we do not want to change the PHP code. Is that Ok with you?

**Comment by mchurchward** [comment]
The second issue is a Boost issue. No one has flagged it as of yet. Probably because it has no real impact.
I was hoping there was some easy fix from the renderer, but probably not. If you have a suggested fix, please provide a pull request and I'll look it over.

**Comment by mchurchward** [comment]
I'm going to close this, since there has been no other action. If there is still anything required, leave a comment to reopen.

**Pull request closed without merging**
