### PR TITLE
display description on course page MOODLE_401_STABLE

### PR DESCRIPTION
**Pull request by rezeau**

### CODE REVIEW

**Comment by Fragonite** [comment]
Hi everyone,

Any idea when this will be merged? Cheers.

**Comment by Fragonite** [comment]
I can confirm this patch works as expected.

**Comment by jzfix** [comment]
we have the same problem. pull request would work. when will it be merged and releases ?

**Comment by berardin** [comment]
Hi everyone,

we have the same issue on our system.
The fix here works fine.

When will it released?

Thank you.

**Comment by rezeau** [comment]
@berardin I'm afraid our friend @mchurchward is too busy with other tasks at the moment to attend the Questionnaire plugin. We'll have to be patient.

**Review by mchurchward — APPROVED** [review]
There was not a lot of detail provided, but since many have tested and approved, I'll approve it.

**Pull request merged**
