### PR TITLE
583 Fix M.core_formchangechecker is undefined

### PR DESCRIPTION
**Pull request by leonstr**
Migrate moodle-core-formchangechecker to core_form/changechecker as the former was removed in Moodle 4.3.3 (MDL-72308).

Proposed fix for #583

### CODE REVIEW

**Review by mchurchward — CHANGES_REQUESTED** [review]
Thank you for this. Can you rebase with the latest MOODLE_401_STABLE to re-enable the CI tests?

Also, will this change allow this to function on Moodle 4.0 and up?

**Comment by leonstr** [comment]
Rebased.

> Also, will this change allow this to function on Moodle 4.0 and up?

Yes, the new core_form/changechecker was added in Moodle 4.0 (MDL-69918).

**Comment by mchurchward** [comment]
Your PR still includes commits from other changes than this one. The PR needs to just include the commit(s) for this PR.
You need to pull the latest MOODLE_401_STABLE locally, then rebase your branch on top of that.
You may need to remove commits that are not part of your PR? Possibly you included some from a different PR?

**Comment by mchurchward** [comment]
Ah. Sorry. I did [fix this here](https://github.com/PoetOS/moodle-mod_questionnaire/commit/852486f30b967d5d61847dfaff9ec8cd23f4c11f). Thanks for your fix as well.

**Pull request closed without merging**
