### PR TITLE
Solve SQL error downloading summary responses text file

### PR DESCRIPTION
**Pull request by crazyserver**

### CODE REVIEW

**Comment by timhunt** [comment]
+1 from me. The change looks correct.

I will leave it for Mike to merge. (I think Mike like there to be a CONTRIB issue created in the Moodle tracker at https://tracker.moodle.org/browse/CONTRIB/component/10231/ - with the issue ID in the commit comment. Look at some other recent commits to get the idea.)

**Comment by crazyserver** [comment]
Thanks Tim!

Opened CONTRIB: https://tracker.moodle.org/browse/CONTRIB-5856

**Comment by crazyserver** [comment]
Any news about the merging of this patch?

**Comment by mchurchward** [comment]
Its on our map and will be dealt with soon.

Mike Churchward | Chief Product Officer | Remote-Learner.net Inc.
mike@remote-learner.net
1.877.299.1293 x113 | 1.519.772.3910 x113 | 1.540.943.7831 x113
http://remote-learner.net | http://remote-learner.ca |
http://remote-learner.co.uk

**Pull request merged**
