### PR TITLE
585 Fix deprecated Behat steps

### PR DESCRIPTION
**Pull request by leonstr**
Update Behat tests replacing steps deprecated by MDL-79029.

Proposed fix for #585

### CODE REVIEW

**Review by mchurchward — CHANGES_REQUESTED** [review]
Thank you for this. Can you rebase with the latest MOODLE_401_STABLE to re-enable the CI tests?

**Comment by leonstr** [comment]
Rebased.

**Comment by mchurchward** [comment]
I don't think you rebased properly. Your PR includes four commits that are not part of your work. Can you make sure you pull the latest questionnaire MOODLE_401_STABLE branch and then rebase your commit on top of that? That should fix your PR.

**Comment by leonstr** [comment]
Hopefully this has been rebased correctly now.

**Review by mchurchward — APPROVED** [review]

**Pull request merged**
