### PR TITLE
New icon feature for Moodle 4

### PR DESCRIPTION
**Pull request by rezeau**
Signed-off-by: rezeau <joseph@rezeau.org>

### CODE REVIEW

**Comment by rezeau** [comment]
Hi Mike, sorry for my too hasty PR with no description...
This PR will make the Questionnaire icon displayed according to the new system in Moodle 4. It uses a monologo icon, which is displayed against a coloured background. I am suggesting using the attached monologo icon, on a green background (MOD_PURPOSE_COMMUNICATION). You can use a more significant monologo icon, of course

.

**Comment by mchurchward** [comment]
I rebased this locally and pushed. Your [commit is in MOODLE_400_STABLE](https://github.com/PoetOS/moodle-mod_questionnaire/commit/c258ed7083d2fc0988df9c6192d7c3fc9e922024).

**Comment by haietza** [comment]
@mchurchward Will the new icon be merged into the main branch? Or should we use MOODLE_400_STABLE?

**Comment by mchurchward** [comment]
The 'main' branch is not used, and has been deleted. Use the latest development branch - MOODLE_400_STABLE.

**Pull request closed without merging**
