### PR TITLE
Prepare for Moodle 4.3 and PHP 8.2.

### LINKED ISSUE #530: Creation of dynamic properties is deprecated
Moodle 4.2.3+ (Build: 20231110)
Php: 8.2.12

PHP 8.2 is showing a lot of deprecated messages:

```
Deprecated: Creation of dynamic property questionnaire::$autonum is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$availability is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$beforemod is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$capabilities is deprecated in mod/questionnaire/questionnaire.class.php on line 100
Deprecated: Creation of dynamic property questionnaire::$closedate is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$cm is deprecated in mod/questionnaire/questionnaire.class.php on line 86
Deprecated: Creation of dynamic property questionnaire::$cmid is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$cmidnumber is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$completion is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$completionexpected is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$completiongradeitemnumber is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$completionpassgrade is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$completionsubmit is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$completionview is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$conditioncompletiongroup is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$conditionfieldgroup is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$conditiongradegroup is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$context is deprecated in mod/questionnaire/questionnaire.class.php on line 89
Deprecated: Creation of dynamic property questionnaire::$context is deprecated in mod/questionnaire/questionnaire.class.php on line 91
Deprecated: Creation of dynamic property questionnaire::$course is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$coursemodule is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$create is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$downloadcontent is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$grade is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$groupingid is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$groupmode is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$id is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$instance is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$intro is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$introformat is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$module is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$modulename is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$name is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$navigate is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$notifications is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$opendate is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$progressbar is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$qtype is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$resp_eligible is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$resp_view is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$respondenttype is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$responses is deprecated in mod/questionnaire/questionnaire.class.php on line 104
Deprecated: Creation of dynamic property questionnaire::$resume is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$section is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$sid is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$survey is deprecated in mod/questionnaire/questionnaire.class.php on line 116
Deprecated: Creation of dynamic property questionnaire::$survey is deprecated in mod/questionnaire/questionnaire.class.php on line 1666
Deprecated: Creation of dynamic property questionnaire::$timemodified is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$visible is deprecated in mod/questionnaire/questionnaire.class.php on line 77
Deprecated: Creation of dynamic property questionnaire::$visibleoncoursepage is deprecated in mod/questionnaire/questionnaire.class.php on line 77
```

### PR DESCRIPTION
**Pull request by lucaboesch**
I have a working branch here that fixes #530.

### CODE REVIEW

**Comment by mchurchward** [comment]
Thanks @lucaboesch . It looks like there are new errors? Probably due to the merges in MOODLE_401_STABLE.

**Comment by lucaboesch** [comment]
Checks are passing again, now, @mchurchward. A branch MOODLE_403_STABLE in your repository would be highly appreciated, I think.

**Comment by mchurchward** [comment]
@lucaboesch I'm not sure [these Behat changes](https://github.com/PoetOS/moodle-mod_questionnaire/pull/542/files#diff-c27bf5ba9d5df002c15c244639371339a4e6c396a2f49d5fcec94511683a8eeaR111) are required. The test pass for me as is.

**Comment by lucaboesch** [comment]
Yes, you are right, @mchurchward.
I've reset the Behat test to the original.

**Review by mchurchward — APPROVED** [review]

**Comment by mchurchward** [comment]
Hi Luca. Sorry, can you rebase again?

**Comment by mchurchward** [comment]
@lucaboesch I'm not sure what happened, but there are 14 commits in this PR and it doesn't seem like they all belong to this PR.

**Comment by lucaboesch** [comment]
That should look better now, @mchurchward .

**Pull request merged**
