### PR TITLE
Add Slider question type compatibility with Feedback features

### PR DESCRIPTION
**Pull request by rezeau**
This should do the trick. Warning: _no negative values_ can be used in Slider if it will be used in Feedback.

### CODE REVIEW

**Comment by mchurchward** [comment]
Thanks for this. Could you add a behat test for this new feedback question? You can use [dropdown](https://github.com/PoetOS/moodle-mod_questionnaire/blob/MOODLE_400_STABLE/tests/behat/dropdown_feedback_question_type.feature), [radio](https://github.com/PoetOS/moodle-mod_questionnaire/blob/MOODLE_400_STABLE/tests/behat/radio_feedback_question_type.feature), [rate](https://github.com/PoetOS/moodle-mod_questionnaire/blob/MOODLE_400_STABLE/tests/behat/rate_feedback_question_type.feature), and [yes/no](https://github.com/PoetOS/moodle-mod_questionnaire/blob/MOODLE_400_STABLE/tests/behat/yesno_feedback_question_type.feature) as examples.

**Comment by rezeau** [comment]
@mchurchward I'm afraid I know nothing of the behat tests; I did try to understand behat once, with the help of Marcus Green) but finally gave up.

**Comment by rezeau** [comment]
@mchurchward I have finally installed Behat components on my localhost machine and created a slider_feedback_question_type.feature script. It works fine on my localhost.
I don't understand while checks fail on my latest commit. What does that error mean "Not enough arguments (missing: "plugin"). " and how can I fix this?

**Comment by rezeau** [comment]
@mchurchward Should I rebase this PR to MOODLE_401_STABLE?

**Comment by rezeau** [comment]
Superseded by #520

**Pull request closed without merging**
