### PR TITLE
New attempt at restoring the radar chart_type to questionnaire feedback

### PR DESCRIPTION
**Pull request by rezeau**
This is my 3rd attempt at restoring this really needed chart type. Don't know why I closed my similar PR. I do hope this new PR can be merged any time soon. It's only a few lines changed in the code; it used to work when I first created it years ago and it disappeared from the code some time ago, no idea why.
Thanks in advance, 
Joseph

### CODE REVIEW

**Review by mchurchward — COMMENTED** [review]
Hi Joseph... I want to make sure this is correct.
There seems to be three sets of logic. One for 'global', one for two feedback sections, and one for more than two feedback sections? And it appears that the graphs offered in the form are different depending on these sections?

Can you describe what the logic does, and the rules that impact them in the PR comments please? Maybe add some comments to the code too.

**Comment by rezeau** [comment]
@mchurchward I'm looking into this, will come back in a couple of days.

**Comment by rezeau** [comment]
@mchurchward 
Here's the work I've done on my new commit [Revision 01 of PR #490]
----
feedback_form.php
Added a number of comments.
Reduced the display of the Chart type dropdown lists from 3 to 1 (or zero).
Logic table:
**Feedback options 	                    | Chart type dropdownn list**
No Feedback messages 	       | Not displayed
Global Feedback        	       | None / Bipolar bars / Vertical Progress bar
Feedback Sections 1 to 2	      | None / Bipolar bars / Horizontal bars
Feedback sections: at least 3  | None / Bipolar bars / Horizontal bars / Rose / Radar

Added a check on the number of questions available, to prevent the erroneous use of the Feedback options -> Feedback sections in case of only one question available in the Questionnaire (which should normally never happen, but...)

Currently on the  Feedback options page there are 2 buttons:
**Save settings** & **Save settings and edit Feedback Sections**. There is no way to quit that page other than clicking on one of the Advanced settings, Questions, Preview, etc. tabs above.
Changed the **Save settings** button to **Save and display**, which saves the current Feedback options and exits the page and goes to the main Questionnaire->View page.

Currently on the  Feedback sections page there are 2 buttons:
**Save changes**, **Delete this section** & **Cancel**. 
There is no way to quit that page other than clicking on one of the Advanced settings, Questions, Preview, etc. tabs above.
New set of buttons as follows:
**Delete this section**: does what it says
**Save changes**: saves current changes
**Feedback options**: saves current changes and goes (back) to the Feedback options page in the case that the number of sections added to the form will now enable more chart types to be available. The Documentation will have to explain that, of course.
**Save and display**: saves the current changes and  and goes to the main Questionnaire->View page.
Removed the **Cancel** button which is no longer needed I think.

**Comment by rezeau** [comment]
Hi @mchurchward
I would really like this PR to be merged ASAP, as I want to add a new option to the Personality test mode. How can I get someone to review my PR so it can be merged?
Thanks

PS. I see "At least 1 approving review is required by reviewers with write access". Who are those "reviewers with write access"?

**Comment by mchurchward** [comment]
Joseph. has this PR been superceded now?

**Comment by rezeau** [comment]
@mchurchward Yes, it's been replaced by  #510

**Comment by rezeau** [comment]
superseded by #510

**Pull request closed without merging**
