### PR TITLE
Fix PHP error message  Warning: Undefined variable $sectionlabel in C…

### PR DESCRIPTION
**Pull request by rezeau**
…:\wamp64\www\htdocs\moodle\mod\questionnaire\questionnaire.class.php on line 4018

### CODE REVIEW

**Comment by rezeau** [comment]
This will fix issue #500

**Review by mchurchward — CHANGES_REQUESTED** [review]
Hi. Sorry for the delay. I am concerned about removing the $sectionlabel, as it is defined in that function, and so may be valid in some cases. Perhaps it just needs to be initialized to tne empty string  to solve this?
Also, can you rebase/reapply against MOODLE_401_STABLE now?

**Comment by lucaboesch** [comment]
#542 will also fix this.

**Comment by mchurchward** [comment]
Since #542  fixed this, I will close this PR.

**Pull request closed without merging**
